# Generated by Django 5.2.12 on 2026-04-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0006_remove_beneficiary_passwordvisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='appointment_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to='consultorio.appointment', verbose_name='Cita de Origen'),
        ),
        migrations.AddField(
            model_name='case',
            name='discapacidad',
            field=models.CharField(blank=True, choices=[('NINGUNA', 'Ninguna'), ('FISICA', 'Fisica'), ('VISUAL', 'Visual'), ('AUDITIVA', 'Auditiva'), ('COGNITIVA', 'Cognitiva'), ('PSICOSOCIAL', 'Psicosocial'), ('MULTIPLE', 'Multiple')], max_length=20, null=True, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='case',
            name='estrato',
            field=models.CharField(blank=True, choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=2, null=True, verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='case',
            name='etnia',
            field=models.CharField(blank=True, choices=[('INDIGENA', 'Indigena'), ('AFRODESCENDIENTE', 'Afrodescendiente'), ('ROM', 'Rom/Gitano'), ('RAIZAL', 'Raizal'), ('PALENQUERO', 'Palenquero'), ('NINGUNA', 'Ninguna')], max_length=20, null=True, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='case',
            name='poblacion',
            field=models.CharField(blank=True, choices=[('DESPLAZADO', 'Desplazado'), ('VICTIMA', 'Victima del conflicto'), ('MIGRANTE', 'Migrante'), ('REINSERTADO', 'Reinsertado'), ('NINGUNA', 'Ninguna'), ('OTRA', 'Otra')], max_length=20, null=True, verbose_name='Poblacion'),
        ),
        migrations.AddField(
            model_name='case',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo del Caso'),
        ),
        migrations.AddField(
            model_name='case',
            name='titular_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cedula del Titular'),
        ),
        migrations.AddField(
            model_name='case',
            name='titular_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Titular'),
        ),
        migrations.AddField(
            model_name='case',
            name='titular_is_beneficiary',
            field=models.BooleanField(default=True, verbose_name='El titular es el beneficiario de la cita'),
        ),
        migrations.AddField(
            model_name='case',
            name='titular_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Titular'),
        ),
        migrations.AddField(
            model_name='case',
            name='titular_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono del Titular'),
        ),
    ]
